### ISSUE TITLE
This Plugin is not for Production? As it shows the field in localhost but not on deployment

### ISSUE THREAD

**Issue by azahid5555** [raykeating/strapi-location-field-plugin#10]
**Here is my Screenshoots**

![Screenshot1](https://github.com/raykeating/strapi-location-field-plugin/assets/48977686/d08efd13-e3fd-4c6a-9a07-675954b8d8ef)
![Screenshot2](https://github.com/raykeating/strapi-location-field-plugin/assets/48977686/040b20df-090d-4f15-821c-f6733f3a18c5)

**Comment by raykeating** [comment]
@azahid5555 I have used the plugin in production.  Can you send a screenshot of the browser console in Strapi, I think it may be CORS related or have something to do with your content security policy

**Comment by azahid5555** [comment]
Hi admin sorry for the delays. here is the screenshot of production admin panel of strapi and the location field is in this small space but didn't seen.

![Screenshot 2023-09-26 113005](https://github.com/raykeating/strapi-location-field-plugin/assets/48977686/a4ca4738-fbc0-461e-ae14-698094adc162)

**Comment by raykeating** [comment]
Have you tried `npm run build`?

**Comment by azahid5555** [comment]
Yeah obviously 😄

**Comment by raykeating** [comment]
Hmm, not totally sure then, I've run this in production for several applications and it worked properly.  

My first thought is that your .env doesn't have the GOOGLE_MAPS_API_KEY on the deployed server.

Or if your `/config/middlewares.js` wasn't properly configured, although if it were this you'd likely run into issues on localhost

```js
module.exports = [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        directives: { "script-src": ["'self'", "'unsafe-inline'", "maps.googleapis.com"] },
      },
    },
  },
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
```

If neither of those work, I'm not sure.

If anyone else is having this issue please thumbs up this comment and I'll take a closer look.

**Comment by james-meneses** [comment]
Mine is showing up but the search doesn't work. I've updated the middleware to bypass CSP but the warning still keeps showing in the console.
