### ISSUE TITLE
Location field not showning when create an entry.

### ISSUE THREAD

**Issue by royjosefsson** [raykeating/strapi-location-field-plugin#4]
### Description
I am not able to see the location field when "Create an entry"
### Screenshots
[Content-Type Builder](https://drive.google.com/file/d/17_knauLN7RbpScUKuXDL4vaH7zN0u9DH/view)
[Content Manager](https://drive.google.com/file/d/1fz0kYonYNJYdL_eKXn6BsVyv_DCJehNS/view?usp=sharing)

### Reproduction:

- Install package

- Add config/plugins.js & add settings to file
- Adjust middlevares.js
- Add GOOGLE_MAPS_API_KEY in .env
- Build project
- Start project with strapi develop

### Expected behavior
When "Create an entry" location field is available

### System information
OS: [Linux Ubuntu 20.04]

strapi: v4.11.1
node: v16.20.0
npm: v8.19.4

Edit:
I don't know what the issue was, but i solved it by reinstalled the project with preferred language as javascript instead.

**Comment by martin-landhi** [comment]
I am using typescript in my project, this plugin seems not support typescript?

**Comment by royjosefsson** [comment]
@martin-landhi 
I didn't get it to work with ts. Not sure if I included a copy-paste typo or something else.

**Comment by rafaneri** [comment]
@royjosefsson can you solve this question?
I've added typescript support to my project, however the field still hidden.

**Comment by rafaneri** [comment]
@royjosefsson 
In my case only the file name, was incorrect! plugin.js but the correct one is plugins.js

**Comment by royjosefsson** [comment]
@rafaneri Did you solve it?
