### ISSUE TITLE
Db table

### ISSUE THREAD

**Issue by martin-landhi** [raykeating/strapi-location-field-plugin#5]
In what table is the information of latitude and location saved?
i could not find the table in the database.

I have meilisearch installed and i want to can search for those field saved. I only see the field "lcoation" as null in the main content-type table

**Comment by raykeating** [comment]
I haven't worked much with the DB under the hood so I wouldn't be totally sure, but I can tell you it's stored as JSON.  I imagine it would be stored in the same way as a JSON field.
