### ISSUE TITLE
API create / update

### ISSUE THREAD

**Issue by martin-landhi** [raykeating/strapi-location-field-plugin#6]
Hi,

How should send the data thought REST api to create or update this custom field?

Really thanks for this work, works perfect.

**Comment by raykeating** [comment]
Hi, sorry for the late response, I must have missed this.  

It's possible that Strapi might accept it if you simply send a JSON object with the same (or similar) key-value structure as the GET response?  To be honest it's not something I thought about or tested when I initially built this plugin.

If that doesn't work, I do plan to look into support for this in the future, but I've been too busy for it lately.  If someone would like to contribute this feature it would be much appreciated

**Comment by raykeating** [comment]
Can confirm this approach will work.  Make sure you provide at least these fields:

```json
{
    "description": "123 Street, New York, NY",
    "place_id": "place-id-returned-from-google-api",
    "lat": 100,
    "lng": 100
}
```

**Comment by mvaisberg** [comment]
Perfect @raykeating it works, thanks
