### ISSUE TITLE
after adding the location field from custom field its not showing

### ISSUE THREAD

**Issue by ghost** [raykeating/strapi-location-field-plugin#8]

**Comment by itekaf** [comment]
I have the same error and any erros on console
My version of Strapi is `4.13.4`

**Comment by screenpunch** [comment]
Same for me.

I've added the Custom content type..
<img width="1121" alt="image" src="https://github.com/raykeating/strapi-location-field-plugin/assets/4116817/78b15cec-de8d-47fe-8595-a93b575fdbe4">

When I create an Entry, I have no Location option..
<img width="1394" alt="image" src="https://github.com/raykeating/strapi-location-field-plugin/assets/4116817/8a159837-a899-45e1-907e-b2024e512dd8">

**Comment by screenpunch** [comment]
Opps, my issue was that I missed the `env()` in `googleMapsApiKey: env("GOOGLE_MAPS_API_KEY"),` and pasted my key between the parenthesis.
Try adding `GOOGLE_MAPS_API_KEY=AABBCC` to your .env file instead.

**Comment by ouipark** [comment]
It still not working for me
![Capture d’écran 2023-10-01 à 18 03 07](https://github.com/raykeating/strapi-location-field-plugin/assets/126383529/96b7bc27-a1c4-488f-a4a9-27992877444f)

**Comment by ouipark** [comment]
We are solved the problem sorry by "yarn build" project to showing custom field on Strapi v4,14,0

**Comment by raykeating** [comment]
Yes, you do need to build the project before the field will appear.  Just added it to the docs
